version: '3.9'

services:
  app:
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
    # command: python3 -m http.server 8002
    build: .
    volumes:
      - ./src/:/app/src/
      - ./manage.py:/manage.py
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:17.2
    volumes:
      - /var/lib/postgres
    ports:
      - 5432:5432
    env_file:
      - .env
