# Generated by Django 5.2.1 on 2025-05-19 17:19

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='captial_longitude',
            new_name='capital_longitude',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='open_street_map',
            new_name='open_street_maps',
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='logic_count_name_d95efa_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=django.contrib.postgres.indexes.GinIndex(fields=['country'], name='logic_count_country_61eb3d_gin'),
        ),
    ]
