# Generated by Django 5.2.1 on 2025-05-19 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_alter_country_flag_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='last_accessed',
            new_name='last_accessed_date',
        ),
    ]
