# Generated by Django 5.2.1 on 2025-05-19 12:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count_of_requests', models.IntegerField(default=1)),
                ('country', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('region', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('last_accessed', models.DateTimeField(null=True)),
                ('independent', models.BooleanField(null=True)),
                ('google_maps', models.URLField(null=True)),
                ('open_street_map', models.URLField(null=True)),
                ('probability', models.FloatField()),
                ('capital_name', models.CharField(max_length=100)),
                ('capital_latitude', models.FloatField()),
                ('captial_longitude', models.FloatField()),
                ('flag_png', models.URLField(null=True)),
                ('flag_svg', models.URLField(null=True)),
                ('flag_alt', models.CharField(max_length=200, null=True)),
                ('coat_of_arms_png', models.URLField(null=True)),
                ('coat_of_arms_svg', models.URLField(null=True)),
                ('borders_with', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
            ],
        ),
    ]
