# Generated by Django 5.2.1 on 2025-05-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_alt',
            field=models.TextField(null=True),
        ),
    ]
